server:
  port: 9191
  servlet:
    context-path: /api/v1

spring:
  application:
    name: auth
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin
      name: db
      profile: local
